### ISSUE TITLE
Create command requires valid connection to MongoDB

### ISSUE THREAD

**Issue by etki** [balmasi/migrate-mongoose#32] opened 2018-02-22 15:59 UTC
I can't create a migration without connecting to MongoDB, which is obviously unnecessary.

**Comment by balmasi** [comment] 2019-07-07 02:40
Excellent catch. I'll update this in the next release

**Comment by balmasi** [comment] 2019-07-07 04:46
Upon closer inspection, I remembered this is by design.

This migrator looks at the db to ensure that:

1. there are no migrations in the db (that could potentially be missing from the file system for some reason) with the same name
2. If there are migrations in the file system that don't exist in the database, auto-import them to the db.
3. as soon as the migration is created, upload the fact that it exists (and is in a down state) to the database so you don't have to rely on devs doing that in a separate step

In essence, this is just for better user experience.

It's much better to have a safe and informative default setting (sync DB on any command and notify the user if anything is wrong or unexpected).

The connection to the database is brief and lightweight.

I'm closing this but am open to further discussion if you feel it's causing a problem

**Closed by balmasi** 2019-07-07 04:46 UTC
